### ISSUE TITLE
Integration zum Server

### ISSUE THREAD

**Issue by pfaffenrodt** [nils-ost/LanPartyOnboardingSystem#1]
Ich hatte mir ein paar gedanken gemacht. Ich schätze, dass wir es so machen könnten.

![Unbenanntes Diagramm drawio (1)](https://user-images.githubusercontent.com/5681688/227626999-fb3160ac-e15c-4bf9-aefb-988f56e5fca5.svg)

Die Idee ist es, dass man es Modular baut. Also das System definiert verschiedene Interfaces, die von dem spezifischem Lan Party Modul implementiert werden müssen.

In unserem Fall für NLPT ist es erst einmal der Login und dann noch die zugewiese IP Adresse.
Diese Informationen sind bereits auf unserem Server vorhanden.

Über die API würde eine Resource "Onboarding" bereistellen.
![image](https://user-images.githubusercontent.com/5681688/227629759-26663e9f-0df3-40e3-b98b-9ed5e7bc4e44.png)

```

# Login

POST /api/routexyz-tbd/login
{
    "username": "random.mail",
    "password": "password"
}
respone:
randomTokenfaerergiaeirtaeiognaeirgneaiorgnaeivbn

# GET

GET /api/routexyz-tbd/onboarding
Authorization: Bearer {{authToken}}

```

**Comment by nils-ost** [comment]
Hi,

danke für deine Gedanken. Aktuell bin ich mir noch nicht sicher, ob wir eine Integration zum NLPT-Server benötigen. Grund hierfür ist, dass LPOS (LanPartyOnboardingSystem) nicht mit Teilnehmer logins arbeitet. Ein Teilnehmer ist identifiziert durch seinen Sitzplatz und PC.

Was natürlich SEHR sinnvoll wäre mit dem NLPT Server abzugleichen, sind die Teilnehmer-Namen und die reservierten Sitzplätze. Hierfür wäre es aber auch möglich vor dem start der LAN-Party einen export im NLPT-Server und einen import in LPOS zu machen. (wahlweise auch über eine API, entweder könnte NLPT-Server diese an LPOS pushen, die API gibts bereits, oder LPOS pullt sich die infos vom NLPT-Server)

Ich habe eben mal ein doc geschrieben, wie ich mir das Onboarding aktuell vorstelle, eventuell hilft das beim Verständnis: https://github.com/nils-ost/LanPartyOnboardingSystem/blob/main/docs/onboarding_sequences.md

**Comment by nils-ost** [comment]
Completed with release of Version v0.4.4
